---
repos:

- repo: https://github.com/charliermarsh/ruff-pre-commit.git
  rev: v0.1.7
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format

- repo: https://github.com/Koihik/LuaFormatter.git
  rev: 29afe10
  hooks:
  - id: luaformatter
